language: ruby
services:
  - memcached
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - jruby-1.7.23
  - jruby-9.0.5.0
  - rbx-2.5.8
  - rbx-3.14
before_install: gem install bundler -v 1.11.2
